name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 16"
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: "Setup npm"
        run: |
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

      - name: Install dependencies
        run: |
          yarn
          ./node_modules/.bin/lerna bootstrap

      - name: Run TSC Build # Run tests of all packages
        run: ./node_modules/.bin/lerna run build

      - name: "Version and publish" # Interesting step
        run: |
          git config user.name "Octocat"
          git config user.email "octocat@github.com"

          ./node_modules/.bin/lerna version --conventional-commits --yes
          ./node_modules/.bin/lerna publish  --yes
